### ISSUE TITLE
Deal with name@usage="primary"

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#125]
Pick one:
- [x] ignore it
- [ ] Copy it to creator
- [x] Just show all the contributors on the search results.
- [ ] Show the first 3 contributors (must get a priority list, e.g. director, collector, producer, photographer, vocalist) on the search result
- [ ] something else?

**Comment by acozine** [comment]
For ingest:
* name@usage="primary" should map to Creator
* an object can only have one Creator
* other name nodes should map to Contributor
i.e. Creator is the primary creative name and Contributors are additional creative names, parallel to Title and Alternate Title
For searching, faceting, and display, according to the spreadsheet:
- [ ] in the facets, Creator and Contributor should combine in a single facet (so if I limit my search with the facet Creator=Honoria Farquart, I should see all records where she is either the Creator or a Contributor) 
- [ ] on the search results, we should only display Creator
- [ ] on the object show page, we should display both Creator and Contributor(s)

**Comment by jcoyne** [comment]
@acozine we are specifically talking about this case: https://github.com/curationexperts/alexandria-v2/blob/master/spec/fixtures/mods/sbhcmss78_FlyingAStudios_collection.xml#L10-L16

where the "Collector" is the primary role. This is about persistence only, not about indexing (search results, facteting or otherwise).

**Comment by mark-dce** [comment]
Given that the [MODS RDF Primer]() recommends expressing roles via predicate relationships rather than as name attributes, we are not implementing the complex name structure currently suggested in the ADRL 2.0 metadata model; instead, each name will be the subject of a specific role-based predicate, see #118.  In search results index view, show all names without roles #131.  In single item show view, show all names with associated roles.
