### ISSUE TITLE
Display copyright_status on image show page

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#165]

**Comment by val99erie** [comment]
The json-ld gem is unable to parse the data that comes from LOC.  I think the problem is an unescaped tab character.  I reported the problem to LOC.  Their reply said that it normally takes at least 5 days to respond to emails.

We can hard-code the labels as a work-around, but I'd rather fix the problem at the source.

Blocked until I hear back from LOC.

**Comment by val99erie** [comment]
See story #114 for URIs

**Comment by mark-dce** [comment]
@val99erie  - it looks like this tab has been in place since 2012, so I'm not sure the LOC is going to take care of it any time soon - it appears to come from here:
http://id.loc.gov/vocabulary/preservation/copyrightStatus/collection_PREMIS.json

The skos JSON version of each predicate seems to be OK - e.g. http://id.loc.gov/vocabulary/preservation/copyrightStatus/cpr.skos.json

We might have to find a workaround rather than having the LOC fix this.

**Comment by val99erie** [comment]
I got a reply from Nate at LOC.  He said he'll fix it, but he didn't say how long it will take.
