### ISSUE TITLE
Merge Local Names

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#178]
Provide a means to merge two local names:
- [x] Select one of the names using the edit icon
- [x] Provide a "Merge Into" option (see wireframe)
- [x] Run a background job to update all reference from the original URI (being edited) to the URI selected in "Merge Into"
- [x] Tombstone the original URI

=======================
![adrl2 - 178 - merge local names](https://cloud.githubusercontent.com/assets/3064318/6911912/d9a4923c-d72c-11e4-9fc1-362590783cdf.png)

**Comment by val99erie** [comment]
I think this should be its own form.  Let's not complicate the create/edit form.

**Comment by mark-dce** [comment]
I'm OK either way - the merge can be indicated in the index list like the edit and delete options.

**Comment by val99erie** [comment]
For background jobs, should we use resque?  Ping @acozine

**Comment by acozine** [comment]
Yes, let's use resque. If we run into issues, I'm happy to investigate alternatives, but let's default to resque.

**Comment by val99erie** [comment]
It shouldn't be a problem to merge records interchangeably among Person, Group, and Organization because all those models can be referenced in the same metadata fields of an Image or Collection (and presumably ETD too).

And it should be no problem to merge a Topic into another Topic, for the same reason.

But, what if someone tries to merge a Person into a Topic?  That type of merge seems incompatible.  For example, a collection has a collector, which is a Person.  If you tried to merge it, then the collector field will have a Topic in it, which supposedly isn't allowed according to the controlled vocabs rules.

What should the behavior be for an incompatible merge?  My suggestion:  Refuse to merge, and print error message to tell the user that type of merge isn't allowed.

**Comment by mark-dce** [comment]
I was probably imagining that the "Merge into" target box would only provide valid merge targets (entries with compatible types) either by dropdown list of prefix narrowing.  So, yes, basically what you're suggesting:  If I'm asking to merge a name, the system should only suggest/provide other potential names - if we allow the box to be free-form entry then it should give some error like "there is no name entry matching the name you have typed".  

The same for topics, so if I say I wan to merge a topic like "California Earthquakes" and then type in a name like "Schwarzenegger, Arnold", the system should tell me that "there is no topic entry matching your input".

*BUT* all of this skirts the perplexing question: is *Flying Spaghetti Monster* a name or a topic ;)

**Comment by val99erie** [comment]
@mark-dce - Notes for demo:

resque-pool should start up on deployment, so background jobs should be running properly.  But if you want to see the resque-web console (to view failed jobs, for example), you'll have to figure out a way to run it and display it in your browser.  Alicia said she was able to do it using an SSH tunnel, but I never got that to work.

If you want to demonstrate failed jobs, you can make a job fail like this:
* Stop the background workers
* Queue a job to merge 2 records
* Delete one of the 2 records
* Start the background workers - now the job will fail because it won't find the record it needs to do the merge

There are other types of failed jobs too, but the auto-suggest and form validation should prevent you from reaching any of those states, so those would be hard to demonstrate at a live demo.  Some other types of failures:
* Passing in a non-existing ID as the merge target
* Attempting to merge a record with itself
* Attempting to merge a local subject with a local name
* Attempting to merge an Image or any type of record that isn't a local authority
