### ISSUE TITLE
Deployment changes for redis & resque

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#282]
For story #178, I'm adding resque for running background jobs.  We'll need to update the deploy scripts to work properly.

Deploy scripts and/or dev environment setup scripts will need to:
- [x] Set up config/redis.yml
- [x] Install redis
- [x] start redis server
- [x] start resque worker(s)

Question:
- [x] Do we want to install resque-pool ?

**Comment by val99erie** [comment]
ping @acozine for help on this story

**Comment by acozine** [comment]
Redis is already installed and running on the ucsb demo server. It should run continuously across code deploys. I'm in favor of resque-pool, but I'm open to arguments against it.

**Comment by acozine** [comment]
I added resque-pool and the restart task in a branch, but when I try to deploy, resque-pool fails with the message:
`/opt/alex2/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:457:in `load': No such file to load -- local_names (LoadError)`
We hadn't deployed to the ADRL sandbox since June 18. I've rolled back my attempted deployments and will address this again in the morning.

**Comment by val99erie** [comment]
I think everything is done for this story.
