### ISSUE TITLE
Double escaped XML

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#394]
004511935.xml has `semi-leptonic tt&amp;macr; decay`

004511940.xml has `"Chican&amp;commat; indigenist"`

004092443.xml has `mas&amp;dotbelow;lah&amp;dotbelow;a`

**Comment by acozine** [comment]
004115341.xml has `The queer fl&acirc;neur abroad` in the title - see  
http://sandbox.curationexperts.com/lib/ark:/48907/f35d8pzb

**Comment by jcoyne** [comment]
Yes, these are exemplars, not an extensive list.

**Comment by jcoyne** [comment]
I believe that only these characters need to be escaped in XML:
```

    ' is replaced with &apos;
    " is replaced with &quot;
    & is replaced with &amp;
    < is replaced with &lt;
    > is replaced with &gt;
```

**Comment by mark-dce** [comment]
The double encoding was an artifact of me downloading and saving the samples from my browser.  The html encoding, however, does occur in the source and shows up with the same problems in UCSB's public catalog.

The double encoding should go away when we complete the downloader #332.  In the meantime, I've reloaded the samples above using curl directly to a file rather than saving from a browser (which introduced the double escapes)

UCSD will need to decide if they want to fix the HTML escaping or live with it.

**Comment by ilessing** [comment]
Mark:  Can you point me to an example of the HTML encoding issue in our OPAC?  I want to look at it closer so I can understand the issue.

**Comment by mark-dce** [comment]
—————————————————

Sys. no. 004511935
Search for supersymmetry at CMS in events with b-tagged jets and missing transverse energy at 8 TeV
http://pegasus.library.ucsb.edu/F/S7QPDBFF11GECIGNRTLIHTBH9H7KE9RRCUQFK4ISP4835UPQS5-28286?func=full-set-set&set_number=003351&set_entry=000001&format=999

Contains html encodings in the “Summary” (520.a)  which should be UTF-8 encoded instead:
&radic;
&rarr;
&macr;

—————————————————

Sys. no. 004511940
Another City is Possible: Mujeres de Maiz, Radical Indigenous Mestizaje and Activist Scholarship
http://pegasus.library.ucsb.edu/F/S7QPDBFF11GECIGNRTLIHTBH9H7KE9RRCUQFK4ISP4835UPQS5-38075?func=full-set-set&set_number=003646&set_entry=000001&format=999

Contains html encodings in the “Summary” (520.a)  which should be UTF-8 encoded instead:
&commat; multiple times

**Comment by mark-dce** [comment]
UCSB indicated they would handle the issue on their end since it also affects their public facing catalog.
