### ISSUE TITLE
db:migrate fails

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#470]
On a clean VM, the first Capistrano run fails on the rake db:migrate step with:
```
== 20150724131151 AddUsernameToUsers: migrating ===============================
-- rename_column(:users, :email, :username)
   -> 0.0083s
-- rename_index(:users, "index_users_on_email", "index_users_on_username")
rake stderr: rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "index_users_on_email" does not exist
```
Did we lose a migration that created index_users_on_email when we switched from local auth to LDAP?

**Comment by val99erie** [comment]
I'm able to reproduce the error in my dev workspace by running:
```
rake db:drop
rake db:create
rake db:migrate
```

Although the error message says that the "index_users_on_email" index doesn't exist, I do actually see it in my database right after the migration fails.  I was able to get rid of the error by swapping the order of the renames in the migration - first rename the index, then rename the column.

This should fix your problem.  However, you might consider changing your cap script to use ```rake db:schema:load``` instead of ```rake db:migrate```.  The ["rails guides" documentation](http://guides.rubyonrails.org/active_record_migrations.html) recommends directly loading the schema file over running migrations:

> There is no need (and it is error prone) to deploy a new instance of an app by replaying the entire migration history. It is much simpler and faster to just load into the database a description of the current schema.

**Comment by val99erie** [comment]
@acozine  I'll assign this story back to you.  If it solves your problem with your cap script, go ahead and close the story.

**Comment by acozine** [comment]
Thanks - this worked like a charm. When I find a way to use ansible to do what capistrano does for us now, I'll be sure we use rake db:schema:load. Meanwhile I'm being lazy - rake db:migrate is the default Cap behavior.
