### ISSUE TITLE
Image indexing error

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#513]
Images are not showing up in the show view - see
http://ucsb.curationexperts.com/lib/ark:/99999/fk4hx1k885

Direct view of the associated image:
http://ucsb.curationexperts.com/images/9b%2F1d%2F98%2F35%2F9b1d9835-bf28-4f07-b08e-9330ac9c1e21%2Foriginal/full/600,/0/default.jpg

Log shows:
```
I, [2016-01-22T15:56:09.392521 #8533]  INFO -- :   Parameters: {"rotation"=>"0", "region"=>"full", "quality"=>"default", "model"=>"riiif/image", "id"=>"9b%2F1d%2F98%2F35%2F9b1d9835-bf28-4f07-b08e-9330ac9c1e21%2Foriginal", "size"=>"600,"}
I, [2016-01-22T15:56:09.393833 #8533]  INFO -- : Riiif resolved 9b%2F1d%2F98%2F35%2F9b1d9835-bf28-4f07-b08e-9330ac9c1e21%2Foriginal to http://127.0.0.1:8080/fedora/rest/prod/9b/1d/98/35/9b1d9835-bf28-4f07-b08e-9330ac9c1e21/original
I, [2016-01-22T15:56:09.405384 #8533]  INFO -- : Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.0ms)
F, [2016-01-22T15:56:09.436647 #8533] FATAL -- : 
Riiif::ImageNotFoundError (Riiif::ImageNotFoundError):
  riiif (0.2.0) lib/riiif/http_file_resolver.rb:73:in `rescue in block (2 levels) in download_file'
  riiif (0.2.0) lib/riiif/http_file_resolver.rb:66:in `block (2 levels) in download_file'
. . . 
```

**Comment by mark-dce** [comment]
@acozine @jcoyne Ian and Alex indicate they've been able to address this issue by reverting the version of riiif:

>Just FYI subsequently later in the afternoon Alex was able to fix the broken image problem by utilizing riiif 0.1.0 code rather than 0.2.0.
We have now deployed that on 2 of our testing ADRL instances:
http://adrlprod.library.ucsb.edu and http://adrlstage.library.ucsb.edu

@alicia - can you test this fix on our demo server

@jcoyne - can you make the necessary changes for alexadria-v2 to be compatible with the riiif 0.2.0 url format - it looks like we're providing a fileset id instead of a file id and that there's been a change from native.jpg to default.jpg

**Comment by jcoyne** [comment]
There are two issues here.  The first is that an update to RIIIF 0.2.0 requires a reindex of the images in order to write the correct URLs for the IIIF v2 spec to Solr. This issue is what Ian and Alex are facing.  This is not what this ticket is about.  This ticket is because upgrading to the hydra-works model puts the image in a slightly different location than it was before. We have not yet updated the indexer to use the correct path for hydra-works.

**Comment by jcoyne** [comment]
The change probably needs to be made here: https://github.com/curationexperts/alexandria-v2/blob/master/app/indexers/image_indexer.rb#L27
