### ISSUE TITLE
Import Rights metadata (copyright, etc.)

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#83]
Three metadata fields come under this general rubric:

- [ ] Copyright Status:
Expressed in MODS: mods:extension/copyrightStatus
Property name: ~~rights~~ see below
Predicate: ~~RDF::DC.rights~~  see below

- [ ] License
Expressed in MODS: mods:extension/copyrightStatement
Property name: license
Predicate: ~~OregonDigital::Vocabularies::CCREL.license~~ see below

- [ ] Use restrictions
Expressed in MODS: mods:accessCondition@type(use and reproduction)
Property name: use_restrictions
Predicate: ~~OregonDigital::Vocabularies::ARCHIVESHUB.useRestrictions~~ see below

**Comment by val99erie** [comment]
Questions for the "license" property:

* [ ] Is "license" a controlled vocabulary or arbitrary text?
* [ ] If it's a controlled vocabulary, what are all the possible licenses?
* [ ] What are the URIs for all the possible licenses?

Questions for the "use_restrictions" property:

* [ ] The same questions as above for "license"

**Comment by mark-dce** [comment]
See the UCSD DAMS rights statements for vocabularies and further detail:
https://docs.google.com/spreadsheets/d/1OjTm1Kuzo-An-THdpUkjwa5puul-b4Lx3SK0lB6rvl8/edit#gid=1349667881

Element | attribute name | predicate | range
------------|--------------------|--------------|---------
Copyright Status | copyright_status | premis:hasCopyrightStatus | premis:copyrightStatus
License | license | dcterms:rights | Oregon Digital Rights URIs
Use Restrictions | use_restrictions | ucsd:rightsNote | refs:Literal

**Comment by val99erie** [comment]
I'm not sure it's correct to map mods:extension/copyrightStatement to the Oregon Digital Rights URIs because then we are throwing data away.  How does this statement map to one of the URIs:
https://github.com/curationexperts/alexandria-v2/blob/mlaster/spec/fixtures/mods/cusbspcsbhc78_100239.xml#L47-L57

For now, I'm marking the story as blocked because Mark wants to talk about it later today.

I think we should close this story and re-write the requirements as 3 separate stories.

**Comment by mark-dce** [comment]
superseded by #114 , #115 , #116
